export const root: string;
export const wrapper: string;
export const hour: string;
export const hourBar: string;
export const hourText: string;
export const hourTextMinutes: string;
export const minute: string;
export const free: string;
export const occupied: string;
