export const root: string;
export const sliderWrapper: string;
export const sliderImage: string;
export const bodyWrapper: string;
export const title: string;
export const subTitle: string;
export const meta: string;
export const equipment: string;
export const timebar: string;
